language: python

python:
  - "3.8"

install:
  - pip3 install virtualenv
  - python3 -m virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt

script:
  - pylint mathgrid
  - pylint --disable=missing-function-docstring tests
  - pytest

branches:
  only:
  - master